nameReference:
  - kind: DataVolume
    version: v1
    fieldSpecs:
    - kind: VirtualMachine
      path: spec/dataVolumeTemplates/metadata/name 
  - kind: DataVolume
    version: v1
    fieldSpecs:
    - kind: VirtualMachine
      path: spec/template/spec/volumes/dataVolume/name
# Change labels based on VM name WITH prefix
# See here for more infomation: https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#supporting-escape-characters-in-crd-path
# Examples here: https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#builtin-namereference
  - kind: VirtualMachine
    version: v1
    fieldSpecs:
    - kind: VirtualMachine
      path: spec/template/metadata/labels/kubevirt.io\/domain 
  - kind: VirtualMachine
    version: v1
    fieldSpecs:
    - kind: VirtualMachine
      path: metadata/labels/app
