apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: base-vm-import-source
  namespace: openshift-virtualization-os-images
spec:
  source:
    registry:
      url: "image-registry.openshift-image-registry.svc:5000/openshift-virtualization-os-images/rhel9-guest:latest"
      pullMethod: node
