<<<<<<< Updated upstream
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev/
=======
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev/
- prod/
>>>>>>> Stashed changes
